//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AUTHOR
{
    public AUTHOR()
    {
        this.Books = new HashSet<Book>();
    }

    public int Id { get; set; }
    public string AuthorName { get; set; }
    public Nullable<System.DateTime> DateOfBirth { get; set; }
    public string Address { get; set; }

    public virtual ICollection<Book> Books { get; set; }
}

public partial class Book
{
    public int BookId { get; set; }
    public string ISBN { get; set; }
    public string BookName { get; set; }
    public Nullable<int> CategoryId { get; set; }
    public Nullable<int> SubCategoryID { get; set; }
    public byte[] Photo { get; set; }
    public Nullable<decimal> Price { get; set; }
    public Nullable<int> PublisherId { get; set; }
    public Nullable<int> AuthorId { get; set; }
    public Nullable<System.DateTime> PublishDate { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<decimal> Total { get; set; }

    public virtual AUTHOR AUTHOR { get; set; }
    public virtual Category Category { get; set; }
    public virtual Publisher Publisher { get; set; }
    public virtual SubCategory SubCategory { get; set; }
}

public partial class Category
{
    public Category()
    {
        this.Books = new HashSet<Book>();
        this.Stocks = new HashSet<Stock>();
        this.SubCategories = new HashSet<SubCategory>();
    }

    public int Id { get; set; }
    public string CategoryName { get; set; }

    public virtual ICollection<Book> Books { get; set; }
    public virtual ICollection<Stock> Stocks { get; set; }
    public virtual ICollection<SubCategory> SubCategories { get; set; }
}

public partial class Order
{
    public Order()
    {
        this.Order_Details = new HashSet<Order_Details>();
        this.Shippings = new HashSet<Shipping>();
    }

    public int OrderId { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
    public Nullable<decimal> GrandTotal { get; set; }
    public Nullable<int> UserId { get; set; }
    public string UserName { get; set; }
    public string DeliveryStatus { get; set; }

    public virtual ICollection<Order_Details> Order_Details { get; set; }
    public virtual ICollection<Shipping> Shippings { get; set; }
    public virtual User User { get; set; }
}

public partial class Order_Details
{
    public int OrderDetailsId { get; set; }
    public string BookISBN { get; set; }
    public string BookName { get; set; }
    public Nullable<int> SalesQuantity { get; set; }
    public Nullable<decimal> SalesPrice { get; set; }
    public Nullable<decimal> SalesTotal { get; set; }
    public Nullable<int> OrderID { get; set; }

    public virtual Order Order { get; set; }
}

public partial class Publisher
{
    public Publisher()
    {
        this.Books = new HashSet<Book>();
    }

    public int Id { get; set; }
    public string PublisherName { get; set; }
    public string PhoneNumber { get; set; }

    public virtual ICollection<Book> Books { get; set; }
}

public partial class Shipping
{
    public int ShippingId { get; set; }
    public Nullable<int> UserId { get; set; }
    public string ShippingAddress { get; set; }
    public string ReceivingPersonName { get; set; }
    public string ReceivingPersonNumber { get; set; }
    public Nullable<int> OrderId { get; set; }
    public string DeliveryProcess { get; set; }

    public virtual Order Order { get; set; }
    public virtual User User { get; set; }
}

public partial class Stock
{
    public int StockId { get; set; }
    public string BookISBN { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<int> SubCategoryId { get; set; }
    public Nullable<int> CategoryId { get; set; }

    public virtual Category Category { get; set; }
    public virtual SubCategory SubCategory { get; set; }
}

public partial class SubCategory
{
    public SubCategory()
    {
        this.Books = new HashSet<Book>();
        this.Stocks = new HashSet<Stock>();
    }

    public int Id { get; set; }
    public string SubCategoryName { get; set; }
    public int CategoryId { get; set; }

    public virtual ICollection<Book> Books { get; set; }
    public virtual Category Category { get; set; }
    public virtual ICollection<Stock> Stocks { get; set; }
}

public partial class User
{
    public User()
    {
        this.Orders = new HashSet<Order>();
        this.Shippings = new HashSet<Shipping>();
    }

    public int UserId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Gender { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string UserRole { get; set; }
    public string UserPhone { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
    public virtual ICollection<Shipping> Shippings { get; set; }
}
